### ISSUE TITLE
green, soul 계정 정상 활동하는지 살펴보고 이후 삭제 조치 고려

### ISSUE THREAD

**Issue by jpham005** [42Statistics/42Stat-Lambda#48]
혹은 본인에게 직접 물어보거나..?
userid:
- 158192
- 158191

**Comment by niamu01** [comment]
예전에 잠깐 물어봤을 땐 피신 합격한 계정에 오류 없는지 확인하려고 합격으로 만들어둔거라 하셨는데 계속 사용하실지 모르겠네요 👀

**Comment by jpham005** [comment]
![Image](https://github.com/42Statistics/42Stat-Lambda/assets/76723089/482518b8-d617-4c83-a507-594e03bbe99a)

테스트 계정으로 결론이 나서, 삭제 조치 후 이슈 종료하겠습니다.
